### ISSUE TITLE
Feedback on homework week #2

### ISSUE THREAD

**Issue by AThraen** [kseniiazar/hyf-homework#2]
Privet!

Overall very well done (I'm impressed)!

One minor detail is that the `<h1>` tag shouldn't contain a line break and the subheader.
https://github.com/kseniiazar/hyf-homework/blob/72ce7f039a7d8275ec2725a7645565c35e7d88bb/html-css/week2/index.html#L11

The appearance of the page is very close to what the designer suggested, the html and css validates perfectly and the mobile (responsive view) looks very good - which makes it hard to find more places to make suggestions on improvements.

When looking at the page as an "iphone" I notice that:
1) The navigation items are very small - which would make it hard to click them with a big thumb like mine. 
2) The same goes for the google maps - that could have easily been full width in mobile view - as it is now, It'll be pretty hard to use it to navigate with.
3) Finally, in responsive view, the designers draft indicated that ideally the icons should be listed 2 and 2.

Other than these minor details I like it! Good job.

**Comment by kseniiazar** [comment]
Made adjustments according to your feedback. Thanks a lot again :)
